# Generated by Django 5.2.3 on 2025-07-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_app', '0002_executionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalcredentials',
            name='municipal_password',
            field=models.BinaryField(max_length=256),
        ),
    ]
