# Generated by Django 5.2 on 2025-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipal_app', '0003_alter_municipalcredentials_municipal_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionhistory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
